### ISSUE TITLE
Option to expand flyout based on bottom to top

### ISSUE THREAD

**Issue by jean3x7** [ShankarBUS/ModernFlyouts#95] opened 2020-10-09 00:58 UTC
I want to dock to the bottom without hide content 

Problem:
![image](https://user-images.githubusercontent.com/32421544/95529334-0274c300-09b1-11eb-8b7a-84f3e6e966cd.png)
![image](https://user-images.githubusercontent.com/32421544/95529345-0d2f5800-09b1-11eb-9fa4-43aa9b23b81d.png)

I want to:
![image](https://user-images.githubusercontent.com/32421544/95529362-18828380-09b1-11eb-8c56-0437e1cd53a2.png)
![image](https://user-images.githubusercontent.com/32421544/95529372-1d473780-09b1-11eb-8fa0-e11f898e0544.png)

Thanks in advance.

**Comment by ShankarBUS** [comment] 2020-10-09 01:02
Thanks for trying out our app and thanks for filling a issue on GitHub

This issue is a part of both #71 & #74

I would need to close this a duplicate of #71. You can make your comments there, alright?

**Closed** 2020-10-09 01:03 UTC

**Comment by ShankarBUS** [comment] 2020-10-09 01:12
Hey @jean3x7, I merged #71 with this issue.

You can make your proposals/comments there 😃
