### ISSUE TITLE
Bug: Win10 Sometimes Bug

### ISSUE THREAD

**Issue by NotoChen** [ShankarBUS/ModernFlyouts#132] opened 2020-10-23 06:28 UTC
**OS Version:**
 - Windows 10 Version: Windows10 Last Version

**ModernFlyouts Version:**
 - Version: Last Version

**Additional context:**
Window10 running for a period of time will be stuck or even crash, the taskbar icon can not be clicked,
And Open software black screen

**Comment by Samuel12321** [comment] 2020-10-23 06:37
duplicate of #116

**Closed by Samuel12321** 2020-10-23 06:37 UTC
Labels: bug, duplicate

**Comment by NotoChen** [comment] 2020-10-23 06:39
thank you
