### ISSUE TITLE
Bug: volume panel is default when changed with touchpad

### ISSUE THREAD

**Issue by hahatulk** [ShankarBUS/ModernFlyouts#228] opened 2020-11-17 19:37 UTC
when i change volume with touchpad three/four fingers gesture, there is no audio flayout shown. 
https://prnt.sc/vkzmmx
https://prnt.sc/vkzm8n

**Comment by Samuel12321** [comment] 2020-11-17 20:04
Hi this is a duplicate of #4. Please see #4 for further updates on this issue.

**Closed** 2020-11-17 20:04 UTC
