### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by danielc0603** [ShankarBUS/ModernFlyouts#201] opened 2020-11-10 03:10 UTC
**Describe the bug:**
Audio/Media flyout isn't working and shows that nothing is playing.

**To Reproduce:**
1. Click on 'volume key'
2. See error 

**Screenshots:**
![unknown (1)](https://user-images.githubusercontent.com/74224007/98622837-68b67380-22d8-11eb-972a-92f88ced0060.png)
![unknown](https://user-images.githubusercontent.com/74224007/98622838-68b67380-22d8-11eb-9fd1-451c551e91a0.png)

**OS Version:**
 - Windows 10 Version: Windows 10 2004 

**ModernFlyouts Version:**
 - Version: v0.8.0.1 

**Additional context:**
Probably just a bug.

**Comment by ShankarBUS** [comment] 2020-11-10 03:12
Why is this issue empty?

**Comment by danielc0603** [comment] 2020-11-10 03:12
> Why is this issue empty?

It was a mistake, I fixed it.

**Comment by ShankarBUS** [comment] 2020-11-10 03:19
This is a know bug.

Duplicate of #29.

Please keep track of that issue. I'll close this as a duplicate.

**Closed** 2020-11-10 03:20 UTC
Labels: Known issue, bug, duplicate, good first issue
