### ISSUE TITLE
program crash

### ISSUE THREAD

**Issue by SouLXH** [ShankarBUS/ModernFlyouts#108] opened 2020-10-14 05:17 UTC
0.6.5
日志名称:          Application
来源:            .NET Runtime
日期:            10/13 星期二 15:52:12
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           TXH‘s-Y7000P
描述:
Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-13T07:52:12.4566391Z" />
    <EventRecordID>9294</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TXH‘s-Y7000P</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()
</Data>
  </EventData>
</Event>

日志名称:          Application
来源:            Application Error
日期:            10/13 星期二 15:52:12
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           TXH‘s-Y7000P
描述:
错误应用程序名称: ModernFlyouts.exe，版本: 0.6.5.0，时间戳: 0x5f4ed7fa
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.488，时间戳: 0x42f14898
异常代码: 0xe0434352
错误偏移量: 0x00129962
错误进程 ID: 0x4684
错误应用程序启动时间: 0x01d6a1312aa77d14
错误应用程序路径: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 5bdad2ee-469a-4c3b-9592-1a271520c1c0
错误程序包全名: 32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg
错误程序包相对应用程序 ID: App
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-13T07:52:12.7065405Z" />
    <EventRecordID>9295</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TXH‘s-Y7000P</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ModernFlyouts.exe</Data>
    <Data>0.6.5.0</Data>
    <Data>5f4ed7fa</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.488</Data>
    <Data>42f14898</Data>
    <Data>e0434352</Data>
    <Data>00129962</Data>
    <Data>4684</Data>
    <Data>01d6a1312aa77d14</Data>
    <Data>C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>5bdad2ee-469a-4c3b-9592-1a271520c1c0</Data>
    <Data>32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg</Data>
    <Data>App</Data>
  </EventData>
</Event>
0.6.8
日志名称:          Application
来源:            .NET Runtime
日期:            10/14 星期三 8:51:44
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           TXH‘s-Y7000P
描述:
Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-14T00:51:44.3462658Z" />
    <EventRecordID>10155</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TXH‘s-Y7000P</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: ModernFlyouts.exe
CoreCLR Version: 5.0.20.45114
.NET Version: 5.0.0-rc.1.20451.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ObjectReference'.
   at WinRT.IObjectReference.ThrowIfDisposed()
   at WinRT.IObjectReference.AsType[T]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.As[A]()
   at ABI.Windows.Foundation.IAsyncOperationWithProgress`2.global::Windows.Foundation.IAsyncInfo.Cancel()
   at System.IO.StreamOperationAsyncResult.CancelStreamOperation()
   at System.IO.StreamOperationAsyncResult.Finalize()
</Data>
  </EventData>
</Event>
日志名称:          Application
来源:            Application Error
日期:            10/14 星期三 8:51:44
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           TXH‘s-Y7000P
描述:
错误应用程序名称: ModernFlyouts.exe，版本: 0.6.5.0，时间戳: 0x5f4ed7fa
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.488，时间戳: 0x42f14898
异常代码: 0xe0434352
错误偏移量: 0x00129962
错误进程 ID: 0x4d40
错误应用程序启动时间: 0x01d6a1b7bd0da0fe
错误应用程序路径: C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: a93b4e7a-05e8-48be-8485-d6ca2097f4d2
错误程序包全名: 32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg
错误程序包相对应用程序 ID: App
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-14T00:51:44.6108142Z" />
    <EventRecordID>10156</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>TXH‘s-Y7000P</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ModernFlyouts.exe</Data>
    <Data>0.6.5.0</Data>
    <Data>5f4ed7fa</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.488</Data>
    <Data>42f14898</Data>
    <Data>e0434352</Data>
    <Data>00129962</Data>
    <Data>4d40</Data>
    <Data>01d6a1b7bd0da0fe</Data>
    <Data>C:\Program Files\WindowsApps\32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg\ModernFlyouts\ModernFlyouts.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>a93b4e7a-05e8-48be-8485-d6ca2097f4d2</Data>
    <Data>32669SamG.ModernFlyouts_0.6.5.0_x86__pcy8vm99wrpcg</Data>
    <Data>App</Data>
  </EventData>
</Event>

**Comment by ShankarBUS** [comment] 2020-10-14 05:32
Duplicate of #100

**Closed** 2020-10-14 05:32 UTC
