### ISSUE TITLE
Bug: The app shuts down when updated and needs to be manually opened instead of reopening by itself

### ISSUE THREAD

**Issue by alexeidrekker** [ShankarBUS/ModernFlyouts#171] opened 2020-11-03 02:40 UTC
Unable to reproduce as the app needs to have an update queued up and I am unable to control this, but it is as the title says.

**Comment by Samuel12321** [comment] 2020-11-03 02:47
duplicate of #159 
Planned for 0.8.2

**Closed by Samuel12321** 2020-11-03 02:47 UTC
Labels: bug
