### ISSUE TITLE
Bug: When try to adjust volume from headset,it shows old layout.

### ISSUE THREAD

**Issue by Sahiru2007** [ShankarBUS/ModernFlyouts#260] opened 2020-11-27 10:43 UTC
**Describe the bug:**

**To Reproduce:**

**Screenshots:**

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 

**Additional context:**

**Comment by ShankarBUS** [comment] 2020-11-27 10:49
Duplicate of #4.

I'll close this issue. You can get further information on #4.

**Closed** 2020-11-27 10:50 UTC
Labels: bug, duplicate, good first issue
