### ISSUE TITLE
Bug: App crashes at random intervals

### ISSUE THREAD

**Issue by pitchtheripoff** [ShankarBUS/ModernFlyouts#131] opened 2020-10-22 20:35 UTC
**Describe the bug:**
The program crashes randomly. I check the task tray, and it just disappears.

**To Reproduce:**
1. Launch the app.
2. Do something else for a couple of minutes.
3. Try using the flyouts.
4. Open task tray.
5. See app crash.

**Screenshots:** -

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 0.7.1

**Additional context:**
I don't know why this happens and it's certainly weird. This was a problem on W10 Version 2004 too.

**Comment by Samuel12321** [comment] 2020-10-23 00:06
hi, thanks for letting us know.
we will try to fix this quickly.
closing this as it is a duplicate of #116

**Closed by Samuel12321** 2020-10-23 00:06 UTC
Labels: bug
