### ISSUE TITLE
Bug: Star menu covers up flyout

### ISSUE THREAD

**Issue by Sebastian1896** [ShankarBUS/ModernFlyouts#188] opened 2020-11-05 20:18 UTC
**Describe the bug:**
When the Start Menu is present the flyout gets lost behind. The windows default one is always on top in any moment.

**OS Version:**
 - Windows 10 Version: 1909

**ModernFlyouts Version:**
 - Version:  v0.8.0.1

**Comment by ShankarBUS** [comment] 2020-11-06 03:35
Same as #32.

I'll merge this with #32 & close this issue as a duplicate of it.

You can keep up with that issue.

Please don't get offended, it'll be better for us to keep the issue count as low as possible in order to track and fix them.

**Closed** 2020-11-06 03:36 UTC
Labels: bug, duplicate, enhancement, good first issue

**Comment by Sebastian1896** [comment] 2020-11-06 03:59
> Same as #32.
> 
> I'll merge this with #32 & close this issue as a duplicate of it.
> 
> You can keep up with that issue.
> 
> Please don't get offended, it'll be better for us to keep the issue count as low as possible in order to track and fix them.

Haha, of course im not offended, anything to help!
