### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by zhizhongpu** [ShankarBUS/ModernFlyouts#835] opened 2021-10-08 22:31 UTC
**Describe the bug:**

Flyout not in primary display after connecting to external display (i.e. primary display)
**To Reproduce:**

1. Stand-alone laptop, with modernflyout open
2. connect an external display, change volume
3. flyout appears on laptop display, not as intended
4. quit modernflyout, restart, flyout appears on primary display; problem fixed
**Screenshots:**

**OS Version:**
 - Windows 10 Version: 
Windows 10 Version: 
v0.9.3.0
**Additional context:**

**Comment by JohnLGalt** [comment] 2021-10-09 22:39
Curious question:

When you connect your external display, is it set to become the main display (in Windows Settings, for example, you select the new, external display, and then select "Make this my primary / main display"?

I suspect your answer is yes, as it works after MFO is killed and restarted it seems to work as you want it to - but just curious to make sure....

**Comment by Samuel12321** [comment] 2021-10-11 22:20
Duplicate of #736 
have added this issue to 736

**Closed as completed by Samuel12321** 2021-10-11 22:20 UTC
Labels: Bug
