### ISSUE TITLE
Bug:When the app starts, it disables the mute setting.

### ISSUE THREAD

**Issue by Jerry4159** [ShankarBUS/ModernFlyouts#275] opened 2020-11-30 00:11 UTC
For example, when I turned off my PC, I mute the audio. And by the time I restart my PC, the launch of this app will enable the sound. 
My English is not good. If you have any questions, just ask me.

Chinese:
如果在关机的时候处于静音状态，重启之后会因为这个软件随开机启动而取消静音，如果这个时候正好有UAC需要允许，就会发出提示音。已经尝试过开机取消该软件启动，就不会取消静音。
需要注意的是我使用的是静音快捷键，而不是将音量调小到0。

**Comment by Cyberdroid1** [comment] 2020-11-30 03:03
Duplicate of #185. Track this issue there.

**Comment by Cyberdroid1** [comment] 2020-11-30 08:58
@ShankarBUS this is a duplicate. Pls close this.

**Comment by ShankarBUS** [comment] 2020-11-30 08:59
Thanks for the reminder!

**Closed** 2020-11-30 08:59 UTC
Labels: bug
