### ISSUE TITLE
Bug: Flyout does not display when apps are in fullscreen mode

### ISSUE THREAD

**Issue by puffycheezball8** [ShankarBUS/ModernFlyouts#227] opened 2020-11-16 17:44 UTC
Bug: Flyout does not display when apps are in fullscreen mode. Please fix.

**Comment by ShankarBUS** [comment] 2020-11-16 17:48
Duplicate of #32.

Please refer #32 for future updates.
I'll now close this issue as a duplicate.

**Closed by ShankarBUS** 2020-11-16 17:48 UTC
Labels: bug

**Comment by puffycheezball8** [comment] 2020-11-17 17:15
Thank you!
