### ISSUE TITLE
ModernFlyouts closes itself every few minutes

### ISSUE THREAD

**Issue by Fritzzin** [ShankarBUS/ModernFlyouts#87] opened 2020-10-06 02:55 UTC
Been using it for 2 days now. I've noticed that sometimes the program ends up closing itself. Decided to take a look at the Event Viewer and these are the results.

Application was installed through the Microsoft Store.

Sorry if there's any information missing, just trying to help out.

![Error](https://user-images.githubusercontent.com/53453816/95153460-e0d3cb80-0765-11eb-83b8-7d05c1a1bc54.png)
![Error2](https://user-images.githubusercontent.com/53453816/95153561-124c9700-0766-11eb-8e4a-582474f1cce0.png)

**Comment by ShankarBUS** [comment] 2020-10-06 03:17
Thanks for reporting this!

But this is a duplicate of #35.
I'm sorry that you experiencing this bug. I will fix this ASAP

**Comment by ShankarBUS** [comment] 2020-10-17 08:18
This is not a dupe of #35. Reopening this now

**Comment by ShankarBUS** [comment] 2020-10-24 04:16
Hey @Fritzzin,

I guess this bug could've been fixed by #113.
See - https://github.com/ShankarBUS/ModernFlyouts/issues/98#issuecomment-710095650

Could you re-check if the bug happens again?

**Comment by Fritzzin** [comment] 2020-10-25 20:49
> Hey @Fritzzin,
> 
> I guess this bug could've been fixed by #113.
> See - [#98 (comment)](https://github.com/ShankarBUS/ModernFlyouts/issues/98#issuecomment-710095650)
> 
> Could you re-check if the bug happens again?

Gonna do a clean install of it and retry, I'll come back with more info after a day or so.

**Comment by ShankarBUS** [comment] 2020-10-25 23:58
Thank you so much @Fritzzin!

**Comment by Fritzzin** [comment] 2020-10-26 22:05
> Thank you so much @Fritzzin!

Well, so far from my testing, everything is working fine and smoothly. Didn't have any problems with it crashing or closing itself. Nothing shows up in the Event Viewer as well.

**Comment by ShankarBUS** [comment] 2020-10-27 00:49
Great!

I will close the issue now.

Feel free to reopen it if the bug happens again 😄

**Closed** 2020-10-27 00:49 UTC
Labels: High Priority, Known issue, bug, good first issue
