### ISSUE TITLE
Not displaying with full screen mode in Movies & TV (standard Windows 10 app)

### ISSUE THREAD

**Issue by pav2805** [ShankarBUS/ModernFlyouts#272] opened 2020-11-29 20:45 UTC
Not displaying with full screen mode in Movies & TV (standard Windows 10 app)

**Comment by Samuel12321** [comment] 2020-11-29 21:00
Hi, thanks for reporting this.
We are aware of this issue (#32). Please see #32 for further updates on this issue.

**Comment by ShankarBUS** [comment] 2020-11-29 21:01
Duplicate of #32.

I do understand your pain because I too experience this issue 😅😂.

We've turned all our focus into this issue and you may expect a quick fix within a couple of weeks.

**Closed by Samuel12321** 2020-11-29 21:00 UTC
