### ISSUE TITLE
Bug: Flyout not appearing when I use Netflix app fullscreen

### ISSUE THREAD

**Issue by johnpauljohnnes** [ShankarBUS/ModernFlyouts#291] opened 2020-12-07 15:58 UTC
**Description:**
The flyout has worked correctly with YouTube full-screen, but whenever I use the Netflix Windows app full-screen, the flyout doesn't appear. I have to exit full-screen to see the volume when I'm changing.

**To Reproduce:**
1. Open Netflix Windows 10 App
2. Enter a video and go full-screen
3. Try to change the volume using media keys (Fn + up and down arrow keys on my laptop)

**Screenshots:**
No screenshot.

**OS Version:**
 - Windows 10 Version: Windows 10 20H2

**ModernFlyouts Version:**
 - Version: v0.8.3 and v0.8.4

**Comment by ShankarBUS** [comment] 2020-12-07 16:09
I do understand the annoyance that this issue cause.

We're tracking and trying to fix this in #32. I'll need to close this issue as a duplicate of it. Please keep up-to-date with #32.

**Comment by johnpauljohnnes** [comment] 2020-12-07 16:11
Sorry for the duplicate!

**Closed** 2020-12-07 16:10 UTC
Labels: bug
