### ISSUE TITLE
Feature Request: [Multi-Language Support 多语言支持] Add support for Chinese-simplified(zh-cn) & Chinese-Traditional(zh-tw)

### ISSUE THREAD

**Issue by Gaoyifei1011** [ShankarBUS/ModernFlyouts#104] opened 2020-10-13 04:25 UTC
希望这个发布到微软商店的应用能够在未来的版本中添加多语言支持
We hope that this Application which is published to Microsoft Store could add a multi-language supprot in a near future version，such as Chinese-simplified(zh-cn)，Chinese-Traditional(zh-tw),and so on.

**Comment by ShankarBUS** [comment] 2020-10-13 05:20
@Gaoyifei1011, Thanks for the reminder! We are aware of this request 😄
Some translation files have been already added.

@Samuel12321 FYI. Did you add the languages mentioned above? Did you check if other languages work?
I can confirm the current supported languages are working fine. We just have to expand it to include more languages.

And another doubt: Since we are making changes to the settings window, we may need to introduce new string resources. How would they be updated?
Should we provide an option to change the language within the app? Should we force users to restart after changing the language?

**Comment by Samuel12321** [comment] 2020-10-13 05:22
It should default to their system default language, whether we need an option to change this i don't know? 

Yes Chinese simplified and traditional have been added

**Comment by Samuel12321** [comment] 2020-10-13 05:29
Duplicate of #17

**Closed by Samuel12321** 2020-10-13 05:29 UTC

**Comment by Gaoyifei1011** [comment] 2020-10-13 11:48
但是目前的这个版本并没有显示不同语言的切换，我的电脑设置的是简体中文，但是应用并没有切换到简体中文，版本号是0.6.8
But now this version does not show different language switch, my computer Settings is simplified Chinese, but the application did not switch to the simplified Chinese character, the version number is 0.6.8

**Comment by Samuel12321** [comment] 2020-10-14 05:04
Please refer to #17 for multi-lingual support.
Multi-lingual support is not available in V0.6.8, it will be available from V0.7.0

**Comment by pzcn** [comment] 2020-10-31 06:12
Hello, the default simplified Chinese language of Windows is zh-CN, and in the latest version 0.7.8.0, the simplified Chinese and traditional Chinese added in the program are zh-Hans and zh-Hant respectively, which do not match zh-CN, so it may be the cause of the problem.

**Comment by Samuel12321** [comment] 2020-10-31 06:19
isnt zh-CN a subset of zh-Hans

**Comment by Samuel12321** [comment] 2020-10-31 21:25
Have added zh-CN to see if that helps.
