### ISSUE TITLE
Bug: Crashes when the cover art hasn't finished download

### ISSUE THREAD

**Issue by exzenous** [ShankarBUS/ModernFlyouts#127] opened 2020-10-21 06:08 UTC
**Describe the bug:**
Crashes when the cover art hasn't finished download and I want to adjust the volume, the window pops up and shows placeholder cover art and crashes. Tried on Apple Music Web Player (Third-party one but should be the same across web based players), Spotify doesn't has this problem, maybe because it could be done just in time.

**To Reproduce:**
1.Skip or wait until the song is changing
2.Adjust the volume

**Screenshot:**
[Imgur](https://imgur.com/QEMiwrc)

**OS Version:**
 - Windows 10 Insider Beta Channel version 20H2 build 19042.572

**ModernFlyouts Version:**
 - Version: 0.7.1

**Additional context:**
It seems that when I switch between Spotify and Apple Music Web App, ModernFlyout doesn't update itself to match the current player

**Comment by ShankarBUS** [comment] 2020-10-22 03:52
This issue is a combo of #100 or #93 and #29.

So I have to close this issue as a duplicate of #100.

Thanks for trying the app and thanks a lot for opening this issue.

I'm sorry for closing this.

**Comment by ShankarBUS** [comment] 2020-10-22 03:53
I will update that issue with your statements though.

You can watch that issue for updates.

**Closed** 2020-10-22 04:42 UTC
Labels: bug, duplicate, good first issue
