### ISSUE TITLE
Not displayed on top of certain windows 10 items.

### ISSUE THREAD

**Issue by lazyb5** [ShankarBUS/ModernFlyouts#242] opened 2020-11-21 17:18 UTC
It doesn't display over certain windows items such as the start menu. But more notably any video apps that use a certain windows modern method for video. Like the Windows store your tube app "mytube". I haven't found any volume OSD app that can show over video on Windows modern apps.

**Comment by Samuel12321** [comment] 2020-11-22 01:35
duplicate of #32 see #32 for updates on this issue.

**Closed by Samuel12321** 2020-11-22 01:35 UTC
