### ISSUE TITLE
Bug: the window does not show in full-screen apps

### ISSUE THREAD

**Issue by macksong** [ShankarBUS/ModernFlyouts#191] opened 2020-11-06 04:04 UTC
**OS Version:**
 - Windows 10 Version: 1909

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**
When video or game is running in full-screen, the window does not show up.

**Comment by ShankarBUS** [comment] 2020-11-06 04:06
DupliCATe of #32.

**Closed** 2020-11-06 04:17 UTC
Labels: bug, duplicate, good first issue
