### ISSUE TITLE
Bug: Controlling volume via bluethooth headset always uses windows standard flyout

### ISSUE THREAD

**Issue by MSchtein** [ShankarBUS/ModernFlyouts#283] opened 2020-12-03 10:19 UTC
**Describe the bug:**
When a Bluetooth headset is used to control the volume, the standard Windows flyout is always used (independent from the chosen flyout). 

**To Reproduce:**
Steps to reproduce the behaviour:

1. Use a BT headset
2. Control the volume via BT headset
3. Standard Windows flyout will appear 

**OS Version:**
 - Windows 10 Home 2004 (but was already the case for previous versions)

**ModernFlyouts Version:**
 - Version: 0.8.0.1 (but was already the case for previous versions)

**Comment by ShankarBUS** [comment] 2020-12-09 12:33
Duplicate of #4

**Closed by ShankarBUS** 2020-12-09 12:33 UTC
Labels: bug
