### ISSUE TITLE
The Window's default flyout and ModernFlyouts are appearing simultaneously sometimes.

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#36] opened 2020-09-17 03:40 UTC
I have noticed several times that both the systemflyout and modernflyout is appearing together sometimes.

![image](https://user-images.githubusercontent.com/51435948/93417391-a5ac4e00-f8c5-11ea-9c7c-b42e1b4ee3c7.png)

Please see to this issue.

**Comment by ShankarBUS** [comment] 2020-09-17 03:42
Do you experience this just after starting the OS? Or does it happen midway?

**Comment by Cyberdroid1** [comment] 2020-09-17 03:45
It happens anytime. Nothing fixed. Also, when I start my pc (not hibernate/sleep), I see the Windows default flyout appear once. I think right after ModernFlyout starts.

**Comment by ShankarBUS** [comment] 2020-09-17 03:48
The first time the OS starts, ModernFlyouts looks for the window's default one and hides it. If not found it will create and hide it. I guess, I have to change this approach

**Comment by Cyberdroid1** [comment] 2020-09-17 03:53
Maybe this process might be bugging out.

**Comment by ShankarBUS** [comment] 2020-09-17 03:54
I don't know how we are going to tackle this. But this will need some time.

**Comment by Cyberdroid1** [comment] 2020-09-17 03:57
Maybe you can ask ADeltaX about this issue, whether he faces it in his app.

**Comment by ShankarBUS** [comment] 2020-09-17 04:03
> in his app.

You mean AudioFlyout by @ADeltaX.

That app just brutally kills the OS flyout at startup and won't show it again. I wanted a different approach, only hide it if we can handle the scene else leave it to the OS.

While we can sure move to brute force, it won't be a good option.

Currently we can disable individual module (audio, brightness, etc) (the OS default one will shown in that case so that users can use OS provided one just for the module they want). If we permanently hid the OS default one, this option will be useless.

**Comment by Cyberdroid1** [comment] 2020-09-17 04:13
Ah, I see. Better keep it non-brutal, so that, in case of a crash, the user doesn't face problem. 

You can try this - disable the windows default flyout when running with a process. When the app crashes/closes/uninstalls, the process will see to it. If it doesn't find the process, it will re-enable the default flyout.

I dont know how you will implement it, but you can try maybe.

**Comment by ShankarBUS** [comment] 2020-09-17 04:15
Two processes? hMmMMmMmMm 🤔🤔🤔🤔

I don't know if MSIX support two applications in one package. I'll try my best.

**Comment by Cyberdroid1** [comment] 2020-09-17 04:33
Noice. Let's see if it is possible.

And also, the ModernFlyout doesn't match to the accent color of the system (see image above). 
Blue is current, purple is old.

**Comment by ShankarBUS** [comment] 2020-09-17 05:09
> And also, the ModernFlyout doesn't match to the accent color of the system (see image above).
Blue is current, purple is old.

![](https://i.kym-cdn.com/entries/icons/original/000/029/223/cover2.jpg)

It works perfectly fine for me. Could you file a separate issue for this?

**Comment by Cyberdroid1** [comment] 2020-09-17 05:34
> Could you file a separate issue for this?

Ok, will do.

**Comment by Samuel12321** [comment] 2020-09-18 08:53
I haven't encountered this issue, have you tried reinstalling.

**Comment by Cyberdroid1** [comment] 2020-09-18 08:54
This issue does not come up every time.

**Comment by ShankarBUS** [comment] 2020-09-20 17:03
@Cyberdroid1, see this - https://github.com/ShankarBUS/ModernFlyouts/issues/34#issuecomment-695809743

**Comment by Samuel12321** [comment] 2020-09-25 04:08
Which version?

**Comment by Cyberdroid1** [comment] 2020-09-25 05:44
v 0.5

**Comment by ShankarBUS** [comment] 2020-11-09 17:48
Does this glitch still occur?

I can't reproduce this on my devices.

I'm pretty sure this wouldn't happen now.

Could you confirm this, @Cyberdroid1?

**Comment by Cyberdroid1** [comment] 2020-11-09 18:10
Well, it happens rarely now and then. The default flyout sometimes just appears together with ModernFlyouts.

**Comment by ShankarBUS** [comment] 2020-11-09 18:13
Ok, thanks 😄!

Ummm.....
Could you provide us the probability ratio of the occurrence?

Like 1% of the time or something...

**Comment by Cyberdroid1** [comment] 2020-11-10 03:28
I think around 5% of the time.

**Comment by ShankarBUS** [comment] 2020-11-10 03:31
That's insanely higher than what I had in mind 😅. I thought it would be around 0.05% of the time.

5% is too high. This could be fixed once we implement #189.

Let's see what happens.

**Closed** 2020-12-09 20:02 UTC
Labels: Known issue, bug, enhancement

**Comment by ShankarBUS** [comment] 2020-12-09 20:04
I'm pretty sure 0dbf40f88b7619aca1eead72ca375ccbf603c6d5 would solve this.

Let's hope this won't occur again.

**Comment by caleb-gamer** [comment] 2023-05-10 05:00
i have never had this issue on windows 10 but now that i moved to windows 11 i have the exact same issue.
