### ISSUE TITLE
Media information from apps like Chrome, Spotify and Groove don't appear anymore

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#93] opened 2020-10-08 04:24 UTC
the media popup still shows up and I can use the controls like pause and play. I just can't see what's playing. This has only started happening since the latest update.

I'm usually using YouTube, YT Music or Spotify.

**Comment by ShankarBUS** [comment] 2020-10-08 04:28
The media flyout doesn't show the playback info (like thumbnail, title, app name)?

Or does it not even list the playback session?

Could you clarify me?

**Comment by Poopooracoocoo** [comment] 2020-10-08 04:39
![image](https://user-images.githubusercontent.com/51363864/95415559-50230880-097c-11eb-8f1d-10b63a1397d7.png)
(argh i forgot how unreliably slow snip & sketch is)

**Comment by ShankarBUS** [comment] 2020-10-08 04:40
Why is the volume control like that?

Does the controls actually work?

**Comment by Poopooracoocoo** [comment] 2020-10-08 04:45
The volume control looks like that because it's muted and because it's 90% opaque?

**Comment by ShankarBUS** [comment] 2020-10-08 04:47
The volume is 0 and muted? Ok!

Does those buttons control the playback?

**Comment by Poopooracoocoo** [comment] 2020-10-08 04:48
yes they do

**Comment by ShankarBUS** [comment] 2020-10-08 04:50
Do other apps such Groove Music, Spotify work?

If not, then .NET 5 migration broke the required WinRT event's invocation.

**Comment by Poopooracoocoo** [comment] 2020-10-08 04:51
Those don't work either.

**Comment by Poopooracoocoo** [comment] 2020-10-08 05:43
In the meantime I've gone back to 0.6.0. :)

**Comment by ShankarBUS** [comment] 2020-10-08 05:52
@Poopooracoocoo 

> In the meantime I've gone back to 0.6.0. :)

![](https://i0.wp.com/comicsandmemes.com/wp-content/uploads/blank-meme-template-139-crying-cat-thumbs-up-1.jpg?fit=530%2C365&ssl=1)

I'm now busy with v0.7 work, once it's done I will fix this one as it's a high priority issue. So please be patient.

**Comment by Samuel12321** [comment] 2020-10-08 08:39
Just noticed a lot of store reported feedback, rolling back the latest release on the store to V6.0. 
Because the store doesn't allow app downgrades, will push a 0.6.6 release which will actually contain 0.6.0

**Comment by ShankarBUS** [comment] 2020-10-09 11:30
Hey guys!

I found the cause of this issue 😑😑.

## ⚡⚡⚡ Microsoft Strikes Again ⚡⚡⚡

This mf shit is causing this bug,
https://github.com/ShankarBUS/ModernFlyouts/blob/2bc6dc9062726c10ee2b9c6f2fc4e9e324b518f7/ModernFlyouts/Controls/SessionControl.xaml.cs#L452

This causes the track change transition to lag.

There will be a transition during track changes. The texts and thumbnail will be faded and be restored once the thumbnail is loaded. But since this function fails to return the stream, the faded items are not restored.

**Comment by ShankarBUS** [comment] 2020-10-11 04:12
Found another related issue

[InvalidCastException when consuming WindowsRuntimeStreamExtensions AsStream result #359](https://github.com/microsoft/CsWinRT/issues/359)

**Comment by ShankarBUS** [comment] 2020-10-11 04:26
We may have to wait till .NET 5 RC2 to have thumbnail.

I will disable the thumbnail till then.

**Comment by Samuel12321** [comment] 2020-10-11 04:27
have they released an ETA for RC2

**Comment by ShankarBUS** [comment] 2020-10-11 05:59
Fixed in 7d94143d755f3e3aa882f2940cf4cc09f5c4f716. But the thumbnail won't be shown until they fix they release .NET RC2.

**Closed by ShankarBUS** 2020-10-11 05:59 UTC
Labels: High Priority, bug

**Comment by Poopooracoocoo** [comment] 2020-10-12 22:53
I'm not getting the app name and icon anymore :/

**Comment by Samuel12321** [comment] 2020-10-12 22:53
which version

**Comment by Poopooracoocoo** [comment] 2020-10-12 23:02
0.6.8.

Oh and every so often when I try to open the settings (which is what I just did to check the version), a black screen will open and the app will go unresponsive, so I'll have to go to terminate it and start it again.

**Comment by Samuel12321** [comment] 2020-10-12 23:08
can you post a screenshot of it

**Comment by Poopooracoocoo** [comment] 2020-10-12 23:10
![image](https://user-images.githubusercontent.com/51363864/95797842-3c8cee80-0d3c-11eb-9757-fd700414032f.png)
I'm using Edge.

**Comment by ShankarBUS** [comment] 2020-10-13 04:48
Oh! Sorry for that pal 😅.

![image](https://user-images.githubusercontent.com/63704247/95816615-29c6e980-0d3d-11eb-8148-0274ec8a912f.png)

https://github.com/ShankarBUS/ModernFlyouts/issues/96#issuecomment-706646266

> I had a shitty method to find the process name from the app id. That's what caused spotify's icon and name to be invisible.
> `var processName = AppId.Remove(AppId.Length - 5, 4);`
> 
> This method returns `Spotife` when the app id is `Spotify.exe` (It removed **"y.ex"** instead of **".exe"**. Thus, ModernFlyouts couldn't fetch the name and icon of the app 🤦‍♂️).
> 
> But it worked for MS Edge & Chrome without any problems because it will return `msedge` because `msedge.exe` has **"e"** at the end and before the **'.'**
> 
> Changing it to **"4"** fixed the issue.
> 
> ```diff
> - var processName = AppId.Remove(AppId.Length - 5, 4);
> + var processName = AppId.Remove(AppId.Length - 4, 4);
> ```
> 
> Sorry for this silly mistake 😅

I changed it to `var processName = AppId.Substring(0, AppId.Length - 4);` and it works fine. I will add this fix in v0.7

**Comment by ShankarBUS** [comment] 2020-10-13 19:18
@Samuel12321

> have they released an ETA for RC2

Seems like .NET 5 RC2 has been released.
https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/

I don't know if the CsWinRT has been fixed for sure.

Let's hope the did fix it and it will work fine.
