### ISSUE TITLE
Feature Request: Add Option To Change Background Colors With Gradients

### ISSUE THREAD

**Issue by Mr-Snow-Skull** [ShankarBUS/ModernFlyouts#243] opened 2020-11-22 06:15 UTC
**Feature Request:**
All ModernFlyout User Will Be Flattered If You Add This Feature.

**Comment by Samuel12321** [comment] 2020-11-22 06:17
Duplicate of #67. Would you mind adding this there. 
Thanks for the suggestion.

**Closed by Samuel12321** 2020-11-22 06:17 UTC
Labels: enhancement
