### ISSUE TITLE
Bug: This app will force exit when watching YouTube Videos.

### ISSUE THREAD

**Issue by bobliboya** [ShankarBUS/ModernFlyouts#133] opened 2020-10-24 05:50 UTC
This app not work when watching a YouTube video. I can change my volume/brightness/CapsLock/NumLock from my keyboard but there is no reaction on the screen (even the System default is not there).

**Comment by Samuel12321** [comment] 2020-10-24 08:06
Hi, which browser are you using and windows version.

**Comment by Samuel12321** [comment] 2020-10-24 08:08
duplicate of #116 and possibly #100

**Closed by Samuel12321** 2020-10-24 08:08 UTC
Labels: bug

**Comment by bobliboya** [comment] 2020-10-24 08:10
> Hi, which browser are you using and windows version.

Google Chrome 86.0.4240.111
Windows 10 1909

**Comment by Samuel12321** [comment] 2020-10-24 08:11
Thanks, see #116 for further updates on this issue
