### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PIndividual** [ShankarBUS/ModernFlyouts#119] opened 2020-10-17 18:51 UTC
The program keeps crashing its self even though I did nothing to the system.

**Comment by Samuel12321** [comment] 2020-10-17 23:36
Thanks for telling us, we will look into this. Any further information, such as what version of modern flyouts you are using and windows version would be helpful.
This appears to be a duplicate of #116 and #100

**Closed by Samuel12321** 2020-10-17 23:36 UTC
Labels: bug, duplicate
