### ISSUE TITLE
if change the volume with a touchpad gesture, a default flyout appears

### ISSUE THREAD

**Issue by klopspafaf** [ShankarBUS/ModernFlyouts#210] opened 2020-11-11 01:39 UTC
**Describe the bug:**

if change the volume with a touchpad gesture, a default flyout appears

**To Reproduce:**
Use touchpad gesture

**OS Version:**
 - Windows 10 Version: 

**ModernFlyouts Version:**
 - Version: 0.8.1

**Additional context:**

**Comment by Samuel12321** [comment] 2020-11-11 01:41
duplicate of #4

**Closed by Samuel12321** 2020-11-11 01:41 UTC
Labels: bug, duplicate
