### ISSUE TITLE
Bug: UI overlap

### ISSUE THREAD

**Issue by fxzxmicah** [ShankarBUS/ModernFlyouts#186] opened 2020-11-05 16:18 UTC
**Describe the bug:**

The left and right pager buttons partly overlap the UI of the central display.

**Screenshots:**

![image](https://user-images.githubusercontent.com/48860358/98266480-529d7000-1fc5-11eb-8b37-db23a3140f3c.png)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.1

**Additional context:**

I don't know if you've noticed this, because my device is a laptop, displayed at 125% zoom

**Comment by ShankarBUS** [comment] 2020-11-05 16:20
It's intended. We are still discussing about a new layout.

Please wait till we conclude a strong decision.

**Comment by fxzxmicah** [comment] 2020-11-05 16:25
OK, I get it.

**Comment by Samuel12321** [comment] 2020-11-05 19:48
Duplicate of #60

**Closed by Samuel12321** 2020-11-05 19:48 UTC
Labels: bug
