### ISSUE TITLE
Bug: ModernFlyouts cannot run under multiple users at the same time

### ISSUE THREAD

**Issue by Senliast** [ShankarBUS/ModernFlyouts#236] opened 2020-11-20 22:52 UTC
**Describe the bug:**
ModernFlyouts cannot run under multiple users at the same time. Idk why it should do any matter, but just giving you know)

**To Reproduce:**
1. Start ModernFlyouts
2. Switch user
3. Try to start ModernFlyouts

**Screenshots:**
(none)

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**
(none)

**Comment by ShankarBUS** [comment] 2020-11-21 04:46
Yes, I tried this too.

I guess it os mostly a problem with how packaged apps run and how Store installs it.

I'll see what I can do.

**Comment by Samuel12321** [comment] 2020-11-21 05:45
That's by design of UWP (or in our case desktop bridge) apps.
There is a way to enable a store app to run on multiple accounts https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/multi-user-applications but i think that it's intended more for xbox.
we just have to use: `<uap:SupportedUsers>multiple</uap:SupportedUsers>`

**Comment by ShankarBUS** [comment] 2020-11-21 06:25
@Samuel12321,

I'm not sure if we should support multi user model.

Because if we were to allow the app to run across multiple users (only one instance for all users), the GSMTC APIs would be clashed with sessions from all users and throw errors too often.

If we were to use one instance per user, we may workaround this.
But we will have future problems when we enable the flyout to be shown atop of the Lockscreen.

So, If we were to enable support for multiple user sessions, it wouldn't cause any problems now. But I'm not sure of the future infrastructure.

**Comment by Samuel12321** [comment] 2020-11-21 06:28
I agree, Will close this issue for now and add it to the list of issues to re evaluate in the future.
Its very easy to just install the app again on the other user account.

**Closed by Samuel12321** 2020-11-21 06:28 UTC
Labels: bug

**Comment by ShankarBUS** [comment] 2020-11-21 06:32
No no, we have to implement this soon.

I'm just worried about how to deal with the Lockscreen in the future.

Users manually installing this app on others user accounts will also lead to the same outcome (clash of flyouts in the Lockscreen [only if we make it to show there, which is not gonna happen soon]).

So, I guess we should provide support multi user app model.

Could you enable it in the package manifest?

**Comment by ShankarBUS** [comment] 2020-11-21 06:36
Not only store apps but all Windows apps are designed to run one instance per session.

So even this were an unpackaged app, the app would run one instance per user session.

But installing the app on all users is something that could be enabled by us.

**Comment by ShankarBUS** [comment] 2020-11-21 06:39
Nah it's too complicated.

Let's not do this.

The legacy flyout is baked into explorer. So, it can run across multiple sessions.

But it's better for us to drop this idea.

**Comment by geext-dk** [comment] 2022-01-03 12:32
Hi! Just want to explain my use case: I have 2 accounts, personal account and work account, on my laptop with Windows 11 (Home). And flyouts don't work in this setup because of this I guess. E.g. I login to one user then switch to another, and flyouts don't work. I have to end the process in the Task Manager and start it again to make it work after user switch.
