### ISSUE TITLE
Feature Request: Please Sir Add Customization OF Background Colors With Dark & Light Theme 💕💕💕

### ISSUE THREAD

**Issue by Mr-Snow-Skull** [ShankarBUS/ModernFlyouts#241] opened 2020-11-21 16:52 UTC
**Additional context:**

Sir If You Add Customization OF Background Colors With Dark & Light Theme, That Would Be A Great Feature & Look So Cool,

Sir i AM Dreaming About This Feature You Already Added, Sir Please Please Please ❤❤❤

**Comment by ShankarBUS** [comment] 2020-11-21 17:01
I will add custom theme support post v1.0 (about 4 months later).

You can define your own colour schemes then 😁.

P.S. Are you Indian? Just asking....

**Comment by Samuel12321** [comment] 2020-11-22 01:39
Great minds think alike, duplicate of #64, See #64 for follow-up on this issue.

**Closed by Samuel12321** 2020-11-22 01:39 UTC
Labels: enhancement

**Comment by Poopooracoocoo** [comment] 2020-11-22 03:36
@Samuel12321 think ya meant #67 

that use of 'sir' lol. they're indian.

**Comment by Samuel12321** [comment] 2020-11-22 06:11
@Poopooracoocoo  yes i did mean #67, thanks for picking that up. 😁

**Comment by ShankarBUS** [comment] 2020-11-22 06:18
@Poopooracoocoo,

> that use of 'sir' lol. they're indian.

Exactly!

**Comment by Mr-Snow-Skull** [comment] 2020-11-28 13:14
> I will add custom theming support post v1.0 (about 4 months later).
> 
> You can define your own colour schemes then 😁.
> 
> P.S. Are you Indian? Just asking....

Yes Sir

**Comment by Cyberdroid1** [comment] 2020-11-28 15:34
> I will add custom theming support post v1.0 (about 4 months later).

Is this still planned or cancelled? I am doubtful on this, since you only have about 3 months.

**Comment by ShankarBUS** [comment] 2020-11-28 15:44
@Cyberdroid1,

Bruh! Why did you have to open up my secret?!

TBH, I only have 2 months (December and January).

What do you want me to say, no?
I was just giving them hope.

**Comment by Cyberdroid1** [comment] 2020-11-28 15:58
> @Cyberdroid1,
> 
> Bruh! Why did you have to open up my secret?!
> 
> TBH, I only have 2 months (December and January).
> 
> What do you want me to say, no?
> I was just giving them hope.

I don't want a no here. I want this feature to be preponed by 2 months now. 


😅 😂😂
