### ISSUE TITLE
Bug: Media Flyout not displayed after install even though enabled

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#195] opened 2020-11-08 21:18 UTC
**Describe the bug:**
Just installed ModernFlyouts on 2 computers, when testing Media Flyout not displayed after install even though enabled in the settings menu. Audio Flyout had to be disabled then re-enabled before it would show up.

**OS Version:**
 - Windows 10 Version: Windows 10 2004 and 2009

**ModernFlyouts Version:**
 - Version: 0.8.1.0

**Comment by ShankarBUS** [comment] 2020-11-09 17:20
Could be the GSMTC bug hitting again?

We thought they fixed it in insider builds.

Are the systems you tested using insider builds or stable builds of Windows 10?

**Comment by ShankarBUS** [comment] 2020-11-10 03:21
Duplicate of #29?

I'll close this for now.

Please reopen if they're not related.

**Closed** 2020-11-10 03:21 UTC
Labels: High Priority, bug
