### ISSUE TITLE
Feature Request: Include toggle in settings to use new Fluent Icons

### ISSUE THREAD

**Issue by Dr-Chronosphere** [ShankarBUS/ModernFlyouts#239] opened 2020-11-21 09:54 UTC
### The Issue:
Windows has been very inconsistent with many icon sets being used all at once. However, work is being done to unify the line icons being used in Microsoft apps across platforms. As seen in beta versions of Chromium Edge, these more rounded icons are starting to make their way to the Windows desktop.

### The Solution:
Microsoft has a [GitHub repository](https://github.com/microsoft/fluentui-system-icons) where their new Fluent icons are being stored. To make this app more future-proof, the ability to switch between current Segoe UI icons and the eventual, more rounded icons should be explored.

**Comment by Samuel12321** [comment] 2020-11-21 09:58
duplicate of #109

**Comment by ShankarBUS** [comment] 2020-11-21 09:58
Oh ho ho,

We tried that #109.

But the outcome wasn't pleasing. So, we reverted it.

I will reconsider this for the v0.9 release

**Comment by Dr-Chronosphere** [comment] 2020-11-21 19:20
> duplicate (sort of) of #109
 So it is... I suppose you could close this request if you see fit. If the toggle bit seems to make this a unique request, I guess you could leave it up. Either that, or I could add this feedback in the comments of #109.

**Comment by Samuel12321** [comment] 2020-11-22 01:27
> I could add this feedback in the comments of #109.

that would be great thanks

**Closed by Samuel12321** 2020-11-22 01:27 UTC
Labels: enhancement
