### ISSUE TITLE
Bug: The program doesn't shown on lockscreen

### ISSUE THREAD

**Issue by validatedev** [ShankarBUS/ModernFlyouts#199] opened 2020-11-10 02:24 UTC
**Describe the bug:**

I cannot see any popup for brightness, caps lock, etc. while the Windows lock screen is activated.

**To Reproduce:**
1. Lock the PC with Win+L combination
2. Try to key combinations which are supposed to expose the ModernFlyouts popup
3. See the popup doesn't shown

**OS Version:**
 - Windows 10 Version: 
Windows 10 20H2

**ModernFlyouts Version:**
 - Version: 
0.8.0.1

**Comment by ShankarBUS** [comment] 2020-11-10 03:25
Duplicate of #32. 😅.

I've merged your statements into #32.

Please keep track of #32 for updates 😄.

**Closed** 2020-11-10 03:25 UTC
Labels: Known issue, bug, duplicate, good first issue
