### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by esadewater** [ShankarBUS/ModernFlyouts#187] opened 2020-11-05 19:40 UTC
**Describe the bug:**
When using volume control of Bluetooth headphones (Surface Studio 2) the classic Windows flyout is used instead of the ModernFlyout

**OS Version:**
 - Windows 10 Version: 20H2

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Comment by DerpySword** [comment] 2020-11-07 20:01
I've encountered a fairly similar bug with Windows Precision Touchpads. If you configure your trackpad in the Windows settings to change the volume it will also not trigger ModernFlyout and will instead display the classic flyout.

**Comment by ShankarBUS** [comment] 2020-11-07 20:03
Oh! Forgot to reply to this issue 🤦‍♂️.

This is a duplicate of #4

**Comment by ShankarBUS** [comment] 2020-11-07 20:04
@DerpySword, you can watch #4 for updates.

I'll close this now as a duplicate.

**Closed** 2020-11-07 20:04 UTC
Labels: bug, duplicate
