### ISSUE TITLE
Doesn't display on apps in fullscreen mode.

### ISSUE THREAD

**Issue by puffycheezball8** [ShankarBUS/ModernFlyouts#211] opened 2020-11-11 19:41 UTC
Doesn't display on apps in fullscreen mode. Please fix ASAP!

**Comment by Poopooracoocoo** [comment] 2020-11-12 00:56
#32?

**Comment by Samuel12321** [comment] 2020-11-12 03:06
duplicate of #32 (Thanks @Poopooracoocoo)

See #32 for updates

**Closed by Samuel12321** 2020-11-12 03:06 UTC
Labels: bug
