### ISSUE TITLE
The standard flyout appears during volume changes through headphones

### ISSUE THREAD

**Issue by vhatsura** [ShankarBUS/ModernFlyouts#106] opened 2020-10-13 13:17 UTC
I'm using `Sony XM-3` headphones and the standard volume flyout appears during volume changes through headphones.

**Comment by ShankarBUS** [comment] 2020-10-13 13:37
This is a duplicate of #4.

Thanks for filling the issue though 😃

**Closed** 2020-10-13 13:41 UTC
