### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by ArmasF31** [ShankarBUS/ModernFlyouts#151] opened 2020-10-29 18:21 UTC
**Describe the bug:**
Hi guys, cool concetp you have here but for me, the app quits after a while, and i have to  relaunch it. 
Has anyone here encountered this issue before?

**To Reproduce:**

**Screenshots:**

**OS Version:**
Im On windws 10 2004
 - Windows 10 Version: 

**ModernFlyouts Version:**
Modern Flyouts Version : 0.7.1
 - Version: 

**Additional context:**

**Comment by ShankarBUS** [comment] 2020-10-29 18:37
Duplicate of #100,

We already fixed it in v0.7.8, please update the app to v0.7.8 on MS Store

**Closed by ShankarBUS** 2020-10-29 18:37 UTC
Labels: bug

**Comment by ArmasF31** [comment] 2020-10-30 07:39
Ok, that fixed it, weird that the store downloaded me an older version.

**Comment by ShankarBUS** [comment] 2020-10-30 07:40
Great! Thank you for your patience! 🤙

**Comment by ArmasF31** [comment] 2020-10-30 07:41
By the way, I'm from Germany and i noticed the translation is a bit odd, if you'd like I could help with that.

**Comment by ShankarBUS** [comment] 2020-10-30 07:44
Yup! @Samuel12321 could you guide @ArmasF31?

**Comment by Samuel12321** [comment] 2020-10-30 08:03
Hi @ArmasF31, mildly concerned that the store gave you an older version. Which windows build are you on?

Regarding the translations, any help you can provide would be greatly appreciated. just modify the "de" xlf file and create a pull request.

**Comment by ArmasF31** [comment] 2020-10-30 08:05
Im on the latest Windows Build, maybe it was just the store being stupid...

**Comment by ArmasF31** [comment] 2020-10-30 08:22
You should be able to see it

**Comment by Samuel12321** [comment] 2020-10-30 08:27
> You should be able to see it

don't quite understand your statement?
