### ISSUE TITLE
When steering volume using bluetooth headphones old windows volume steering appears

### ISSUE THREAD

**Issue by Lukasz-egg** [ShankarBUS/ModernFlyouts#207] opened 2020-11-10 17:02 UTC
When I use my bt headphones to change volume, old windows volume control appears, but without media steering, when I change volume using keyboard old windows instantly dissapears and new volume control appears.

[Video.zip](https://github.com/ShankarBUS/ModernFlyouts/files/5518919/Video.zip)

**Comment by Lukasz-egg** [comment] 2020-11-10 17:05
I use windows version 20H2, 0.8.1.0 app version

**Comment by ShankarBUS** [comment] 2020-11-10 17:28
Duplicate of #4.

Please keep up-to-date with #4.

I'll close this issue as a duplicate of #4.

**Closed** 2020-11-10 17:28 UTC
Labels: Known issue, bug, duplicate, good first issue
