### ISSUE TITLE
Bug: Show "Overtype Mode" or "Insert Mode" when "Insert" is used in key combination

### ISSUE THREAD

**Issue by lsylusiyao** [ShankarBUS/ModernFlyouts#276] opened 2020-11-30 09:28 UTC
**Describe the bug:**
When "Ctrl+Insert" (Copy in XShell or Windows Terminal) or "Shift+Insert" (Paste) , the dialog of "Overtype Mode" or "Insert Mode" show on the screen. However, Windows itself doesn't consider it as the switch of Overtype or Insert. 

**To Reproduce:**

Just press "Ctrl+Insert" or "Shift+Insert" and the bug will show.

**Screenshots:**

Maybe it's not necessary :)

**OS Version:**
Windows 10 2004

**ModernFlyouts Version:**
 - Version: 0.7.8.0, installed from chocolatey

**Additional context:**

**Comment by ShankarBUS** [comment] 2020-11-30 09:39
Duplicate of #90.

**Closed by ShankarBUS** 2020-11-30 09:39 UTC
Labels: bug
