### ISSUE TITLE
Bug: Notification icon showing up even though the option is off

### ISSUE THREAD

**Issue by erayrafet** [ShankarBUS/ModernFlyouts#284] opened 2020-12-04 08:08 UTC
**Describe the bug:**

I keep the show notification icon toggle off, but after a reboot of the computer, the icon shows up again and again and I need to toggle the option on and off to fix it.
**To Reproduce:**
1. Go to 'Personalization'
2. Click on 'Show icon on system tray area' to turn it off.
3. Reboot the computer.
3. See error

**Screenshots:**
![image](https://user-images.githubusercontent.com/34194191/101137876-26066380-3618-11eb-920b-ac4f890403c2.png)

**OS Version:**
 - Windows 10 Version: 20270

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**
I have the top setting on.
![image](https://user-images.githubusercontent.com/34194191/101138073-5d751000-3618-11eb-8631-63a1b28df3de.png)

**Comment by Cyberdroid1** [comment] 2020-12-07 16:42
Duplicate of #281.

**Closed** 2020-12-09 12:32 UTC
Labels: bug, duplicate
