### ISSUE TITLE
Feature Request: Showing audio flyout when music track changes

### ISSUE THREAD

**Issue by wfsg00098** [ShankarBUS/ModernFlyouts#192] opened 2020-11-08 08:26 UTC
Playing with foobar2000. 
Audio flyout shows up when pause or play.
So can you make it shows when music track changes?
THANKS

(sorry for poor english)

**Comment by Samuel12321** [comment] 2020-11-08 08:42
Closing as duplicate of #78

**Closed by Samuel12321** 2020-11-08 08:42 UTC
Labels: duplicate

**Comment by wfsg00098** [comment] 2020-11-08 08:51
Sorry for that. Maybe there is a bug which blocks it showing up, but I cannot reproduce it.

**Comment by Samuel12321** [comment] 2020-11-08 08:52
All good.
It hasn't been added yet, see #78. Planned for 0.7.4
