### ISSUE TITLE
Feature Request: Ability to set cooldown (in seconds) for hiding flyouts.

### ISSUE THREAD

**Issue by Tropix126** [ShankarBUS/ModernFlyouts#149] opened 2020-10-29 05:38 UTC
**Is your feature request related to a problem? Please describe:**
Sometimes I feel that the default time that the flyout stays on the screen is a bit too long, and it would be nice if users could customize this aspect.

**Describe the solution you'd like:**
Ability to adjust how long flyouts stay on the screen before auto-hiding. Could just be a slider in the settings menu with 1-10 seconds as options, or a textbox with amount of milliseconds before fading.

**Describe alternatives you've considered:**
None.

**Additional context:**
None

**Comment by ShankarBUS** [comment] 2020-10-29 05:40
Duplicate of #53 

I already implemented it locally on my PC. I will push the features to GitHub soon.

**Closed by ShankarBUS** 2020-10-29 05:40 UTC
Labels: enhancement
