### ISSUE TITLE
App is crashing a lot

### ISSUE THREAD

**Issue by Cyberdroid1** [ShankarBUS/ModernFlyouts#123] opened 2020-10-18 06:30 UTC
**Describe the bug**
The app crashes now and then

**Screenshots**

![image](https://user-images.githubusercontent.com/51435948/96359704-717db480-1133-11eb-832b-cec6983825f8.png)

**OS Version:**
 - Windows 10 Version 2009

**ModernFlyouts Version:**
 - Version: [0.7.0]

**Comment by Samuel12321** [comment] 2020-10-18 07:50
Thanks @Cyberdroid1, we are aware of some stability issues. 
Thanks for providing crash report. 
Will close this as it is a duplicate of #100 and #116

**Closed by Samuel12321** 2020-10-18 07:50 UTC
Labels: bug
