### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by Samkunmiayo** [ShankarBUS/ModernFlyouts#221] opened 2020-11-15 22:27 UTC
**Is your feature request related to a problem? Please describe:**

Amazing app! Would be amazing to have the ability to seek the current audio in the timeline info section.

**Describe the solution you'd like:**

Addition of a seek feature similar to the volume slider to enable the user go to a certain section of the song or podcast, like in spotify for example

**Describe alternatives you've considered:**

**Additional context:**

![image](https://user-images.githubusercontent.com/51705261/99198620-940ff580-27e5-11eb-9133-4b7b1ae41513.png)

**Comment by Poopooracoocoo** [comment] 2020-11-15 23:56
#97

**Comment by Samuel12321** [comment] 2020-11-16 20:40
Closing as a duplicate of #97
However reopening #97. @Samkunmiayo see #97 for further updates on this.

**Closed by Samuel12321** 2020-11-16 20:40 UTC
Labels: enhancement
