### ISSUE TITLE
Feature: Flyout for function key enabled / disabled

### ISSUE THREAD

**Issue by Samuel12321** [ShankarBUS/ModernFlyouts#57] opened 2020-09-25 03:38 UTC

**Comment by ShankarBUS** [comment] 2020-09-25 04:08
Do you refer to the <kbd>Fn</kbd>?

That key is not available on my external keyboard (only present on Laptop's keyboard). I guess they are only available for laptops. Correct me if I'm wrong

**Comment by Samuel12321** [comment] 2020-09-25 04:10
> Do you refer to the Fn?
> 
Yes
> That key is not available on my external keyboard (only present on Laptop's keyboard). I guess they are only available for laptops. Correct me if I'm wrong

Seems its different for different manufacturers, my desktop keyboard has one.

**Comment by ShankarBUS** [comment] 2020-09-25 04:33
But why would that be necessary?

**Comment by Samuel12321** [comment] 2020-09-25 04:43
Very easy to accidentally press this key, and then f1 to f12 have completely different functions

**Comment by ShankarBUS** [comment] 2020-09-25 05:05
If you really mean the <kbd>Fn</kbd> key aka the **"Function _Key_"**, we are gonna have some hurdles

But if you refer to the **"Function _Keys_"** i.e. <kbd>F1</kbd>, <kbd>F2</kbd>, ... That would achievable 😁

This what I mean only my laptop has the <kbd>Fn</kbd> key (by default the keys from 
<kbd>F1</kbd> to <kbd>F12</kbd> have specific functions in laptops i.e to control brightness, volume, media, airplane mode. The <kbd>Fn</kbd> key just turns off the the OEM specific functions and make those keys act as intended i.e. as normal function keys like those in external keyboard)

![Laptop with <kbd>Fn</kbd> key](https://user-images.githubusercontent.com/63704247/94228428-88592e80-ff1a-11ea-81fc-602f6fc7c880.jpg)

![Keyboard with only function keys](https://user-images.githubusercontent.com/63704247/94228498-c0f90800-ff1a-11ea-9340-f48d11569b48.jpg)

**Comment by Samuel12321** [comment] 2020-09-25 05:09
> If you really mean the Fn key aka the **"Function _Key_"**, we are gonna have some hurdles

yes this is the key i meant.

**Comment by ShankarBUS** [comment] 2020-09-25 05:12
👀

https://stackoverflow.com/a/42206057

https://stackoverflow.com/questions/49945785/detect-fn-key-with-js

**Comment by Samuel12321** [comment] 2020-09-25 05:21
> Most FN keys are implemented in firmware and won't be recognized by applications

How helpful of device manufacturers. (insert facepalm)

**Comment by Samuel12321** [comment] 2020-09-25 05:21
just checked mine is firmware based

**Comment by Samuel12321** [comment] 2020-09-25 05:22
May have to leave this one for now, looks like it may be more trouble than its worth.

**Comment by ShankarBUS** [comment] 2020-11-09 17:52
As we already know that the <kbd>Fn</kbd> key is undetectable by programs, I'm gonna close this close now.

Feel free to reopen it 😄.

**Closed** 2020-11-09 17:53 UTC
Labels: enhancement, invalid
