### ISSUE TITLE
No change in media pop-ups

### ISSUE THREAD

**Issue by fxzfdazy** [ShankarBUS/ModernFlyouts#94] opened 2020-10-08 07:32 UTC
The media popup sometimes doesn't change, even if I close the app or change a song, it still looks the same

**Comment by ShankarBUS** [comment] 2020-10-08 07:48
I'm sorry for your inconvenience 😅.

Duplicate of #29, we can continue our conversation there

**Closed** 2020-10-08 07:48 UTC
