### ISSUE TITLE
Bug: Cannot reset the Flyout default position

### ISSUE THREAD

**Issue by ModerRAS** [ShankarBUS/ModernFlyouts#226] opened 2020-11-16 11:54 UTC
**Describe the bug:**

When I set a very large Flyout default position (like 5000,6000) and set the flyouts as the default position, I will not see it. I also cannot to reset it.

**To Reproduce:**

1. Open the settings
2. Change the  Flyout default position
3. Click Align to default position

**Screenshots:**

![bug](https://user-images.githubusercontent.com/28183976/99249245-c00e9380-2844-11eb-8652-c454c6bd28b7.gif)

**OS Version:**
 - Windows 10 Version:  Windows 10 2004

**ModernFlyouts Version:**
 - Version: 0.8.0.1

**Additional context:**

I think it needs a reset button.

**Comment by ShankarBUS** [comment] 2020-11-16 11:58
Ughhhhh, why would you do that! 😤😬

Duplicate of #141 and will be fixed by #179.

For a temporary recovery you can do this
https://github.com/ShankarBUS/ModernFlyouts/issues/141#issuecomment-716099619

**Comment by ModerRAS** [comment] 2020-11-16 12:13
> 
> 
> Ughhhhh, why would you do that! 😤😬
> 
> Duplicate of #141 and will be fixed by #179.
> 
> For a temporary recovery you can do this
> [#141 (comment)](https://github.com/ShankarBUS/ModernFlyouts/issues/141#issuecomment-716099619)

I just tried to place it in the lower middle of the screen, but there is no way to reset it after the wrong setting. Setting it to this size just means that I can't reset it.  (￣ε(#￣) 

Glad to see it will be fixed.

**Comment by Samuel12321** [comment] 2020-11-16 20:34
Hi @ModerRAS, Thanks for reporting this. 
As @ShankarBUS Pointed out this is a duplicate of #141 with a solution of #179 
Will close this as a duplicate of #141, Please see #141 for follow-up on this issue.

**Closed by Samuel12321** 2020-11-16 20:34 UTC
Labels: bug

**Comment by ShankarBUS** [comment] 2020-11-18 18:02
@ModerRAS,

![image](https://user-images.githubusercontent.com/63704247/99569158-4c13ed00-29f6-11eb-8405-f6f18e98876a.png)

Happy now?

**Comment by ModerRAS** [comment] 2020-11-19 00:37
> 
> 
> @ModerRAS,
> 
> ![image](https://user-images.githubusercontent.com/63704247/99569158-4c13ed00-29f6-11eb-8405-f6f18e98876a.png)
> 
> Happy now?

That's great!
≧▽≦
