### ISSUE TITLE
Add transparency to flyouts

### ISSUE THREAD

**Issue by Poopooracoocoo** [ShankarBUS/ModernFlyouts#47] opened 2020-09-20 14:11 UTC
The native "flyouts"/pop-ups in Windows 10 are a bit transparent and I've come to miss that using ModernFlyouts.

**Comment by ShankarBUS** [comment] 2020-09-20 14:26
But they will look ugly while using shadows.

**Comment by Poopooracoocoo** [comment] 2020-09-20 14:41
take a look at macOS' Control Centre. It has both transparency and a shadow (with blur/vibrancy :p): 
![image](https://user-images.githubusercontent.com/51363864/93713937-843bb280-fba2-11ea-9ced-1af0907d642c.png)
from [how to geek](https://www.howtogeek.com/680008/how-the-new-control-center-in-macos-big-sur-works/)

**Comment by ShankarBUS** [comment] 2020-09-20 14:42
That effect could be achieved if we use **xaml islands + WinUI** instead of **WPF**. There are no recent plans to move to WinUI or islands. I will try my best.

**Comment by Poopooracoocoo** [comment] 2020-09-20 14:44
I'm not particularly after blur, just transparency :)

**Comment by ShankarBUS** [comment] 2020-09-20 14:47
I will provide you some mockups. Tell me if they look good.

Another thing to note : You may be using v0.4.0, the mockup I'm gonna provide will be from v0.5.0 which will be released tomorrow.

**Comment by ShankarBUS** [comment] 2020-09-20 15:35
@Poopooracoocoo,

![image](https://user-images.githubusercontent.com/63704247/93714976-dfaa7800-fb83-11ea-9869-c8fdbe712e0d.png)

![image](https://user-images.githubusercontent.com/63704247/93715008-1da79c00-fb84-11ea-951e-6152e8e74a4b.png)

![image](https://user-images.githubusercontent.com/63704247/93715094-bdfdc080-fb84-11ea-8670-33014e42d0e3.png)

![image](https://user-images.githubusercontent.com/63704247/93715107-dff74300-fb84-11ea-95c3-5ebcd4957b91.png)

Now what? Will you suggest transparency now?

**Comment by Cyberdroid1** [comment] 2020-09-20 17:28
Looks too good to be true, actually 😂. But you will make it true, won't you?

Looks awesome to me!

**Comment by ShankarBUS** [comment] 2020-09-20 17:35
@Cyberdroid1 @Poopooracoocoo

Seriously pals? 😂. It looks good? 😂😂😂

It's relatively easy, just need to add an option in the settings that will reduce the opacity (as a slider : 0% opaque to 100% opaque) or just toggle transparency (a toggle switch to switch between 90% opaque or 100% opaque). Could be easily done in v0.6.0

By default it will be opaque, users can change this.

What would you prefer a opacity slider or a toggle switch (translucent/opaque)?

**Comment by Cyberdroid1** [comment] 2020-09-20 19:07
I would vote for slider, as every user has different needs. 
Maybe keep the default setting to 90%.

**Comment by ShankarBUS** [comment] 2020-09-26 02:44
@Cyberdroid1,

> Maybe keep the default setting to 90%.

Should we really do it?

**Closed** 2020-09-26 02:46 UTC
Labels: Low Priority, UI Improvement, enhancement, good first issue

**Comment by Cyberdroid1** [comment] 2020-09-26 02:47
Yup! Is there any problem though in this?

**Comment by ShankarBUS** [comment] 2020-09-26 02:50
Implemented in 77fcd9290953b28aeb3833a7490eca8133dcb055

But the problem is the transparency won't affect the contents only the background color. **"Zero"** opacity will look like this

![image](https://user-images.githubusercontent.com/63704247/94328544-10017480-ffd1-11ea-8fb6-c44114edad4b.png)

**Comment by ShankarBUS** [comment] 2020-09-26 02:51
> Yup! Is there any problem though in this?

But changing the default from v0.5 to v0.6 will be unwanted and unpleasant to users, right? So lets keep the default 100% for now. The users can change it by themselves

**Comment by Cyberdroid1** [comment] 2020-09-26 04:30
Ah, ok. Sure, its your call. Any level would be good as default.

**Comment by Samuel12321** [comment] 2020-11-06 05:16
> That effect could be achieved if we have used **xaml islands + WinUI** instead of **WPF**. There are no recent plans to move to WinUI or islands. I will try my best.

What about XAML Islands + WPF? Currently looking at it for settings menu (see Discord).

**Comment by ShankarBUS** [comment] 2020-11-06 06:36
It's absolutely possible to use xaml islands in WPF just for the settings window (like PowerToys settings).

But for the flyout window it would work (we can only have rectangular non-transparent window with Xaml Islands).

I said this many times in this repo and even on discord!!

So, let's come back to your point.

Use xaml islands just for settings window. But the UI will be fragmented between a UWP project and a WPF project. It'll be a hell to set up and maintain. Literally hard as hell to setup MVVM.

Hard to maintain UI consistency, breaking bugs, hard to track exceptions. There would be frequent crashes.

I'm never gonna use XAML islands (WinUI 2)!!!

We can reconsider this once WinUI 3 has acrylic or reveal.

Oh wait! Even MS doesn't care about acrylic or reveal. They're removing it!!!!

So no WinUI 3 or XAML islands (WinUI 2)!

That's it. I said this many times!

**Comment by Samuel12321** [comment] 2020-11-06 06:41
Sorry, probably wrong issue to post this on. Wasn't really think about the flyout, just the settings menu. This is well outside my area of expertise, so was just checking what would be needed. If you think it's not worth it, will drop it.
