### ISSUE TITLE
Lock key flyouts do not respect PowerToys Keyboard Manager

### ISSUE THREAD

**Issue by watermarkhu** [ShankarBUS/ModernFlyouts#85] opened 2020-10-05 09:32 UTC
If for example the Caps Locks and Left Control are remapped to each other in the PowerToys Keyboard Manager, pressing Caps Lock still enables the flyout. Also, if the key is remapped, the value of the lock key in ModernFlyout is flipped, while the real value hasn't changed. 

Example if the CapsLocks and Left Control are remapped:

**CapsLock real value**, _ModernFlyout value_

**CapsLock is on**:   CapsLock -> _CapsLock is off_, CapsLock -> _CapsLock is off_, Left Control: **CapsLock is off** -> _CapsLock is off_
**CapsLock is off**:   CapsLock -> _CapsLock is on_, CapsLock -> _CapsLock is on, Left Control: **CapsLock is on** -> _CapsLock is on_

**Comment by ShankarBUS** [comment] 2020-10-05 10:25
Duplicate of #84

**Closed by ShankarBUS** 2020-10-05 10:25 UTC
