### ISSUE TITLE
Bug: My crash issue is caused by Spotify

### ISSUE THREAD

**Issue by lucellent** [ShankarBUS/ModernFlyouts#139] opened 2020-10-24 23:15 UTC
I've been reading that other people have been having their app also crash a lot of times during the day, mine started happening weeks ago. I just realized that it crashed the most when using Spotify.

What basically happens is, I open Spotify, play a song, and after a few minutes, if I use my dedicated keyboard keys to change songs, volume etc. the pop-up would not appear because the app has crashed, so I have to re-open it. The volume itself (for examples) changes normally, I just don't see it visually

Windows 10 Home 2004

ModernFlyouts v0.7.1

**Comment by ShankarBUS** [comment] 2020-10-25 00:40
This is a duplicate of #100 and has been already fixed, isn't it @Samuel12321?

**Comment by Samuel12321** [comment] 2020-10-25 00:41
yes, i think so

**Closed by Samuel12321** 2020-10-25 00:41 UTC
Labels: bug
