### ISSUE TITLE
Media Flyout no longer displaying media

### ISSUE THREAD

**Issue by JDar2K** [ShankarBUS/ModernFlyouts#89] opened 2020-10-07 00:46 UTC
I'm currently using MusicBee, but I checked with Spotify as well and no dice.

**Comment by ShankarBUS** [comment] 2020-10-07 01:02
Are you currently using Windows 10 2004/2009?

**Comment by JDar2K** [comment] 2020-10-07 01:04
Yes

**Comment by ShankarBUS** [comment] 2020-10-07 01:06
Then see #29.

The app has to restarted to show them

We are trying to find a way to tackle this bug

**Comment by ShankarBUS** [comment] 2020-10-07 01:07
Duplicate of #29

**Closed** 2020-10-07 01:06 UTC
Labels: bug, duplicate, good first issue
